---
    - set_fact:
          scripttorun: db2_backup_purescale.sh
      tags: always

    - name: Create Local Directory
      local_action: 
          module: file
          path: /tmp/db2bkpreports/ps
          state: directory
          mode: 0777
      become: false
      run_once: true
      tags: createlocdir

    - name: Copy - Script to target node
      template: src="{{ scripttorun }}" dest="{{ logsdir }}/{{ scripttorun }}" mode=0755
      tags: copyscript

    - name: "Run - Script - \"{{ scripttorun }}\""
      shell: |
              TGTUSR="{{ item }}"
              perl -p -i -e 's/\r//g' {{ logsdir }}/{{ scripttorun }}
              su ${TGTUSR} -c "{{ logsdir }}/{{ scripttorun }} ${TGTUSR}"
      loop: "{{ db2ilist.stdout_lines }}"
      tags: runscript

    - name: Fetch report files from all servers to reporting server
      fetch: 
        src: "{{ logsdir }}/daily_report_{{ item }}.final" 
        dest: "/tmp/db2bkpreports/ps/daily_report_{{ item }}_{{ inventory_hostname }}.final" 
        flat: yes
      loop: "{{ db2ilist.stdout_lines }}"
      tags: fetchfiles

    - command: date +'%Y%m%d%H%M%S'
      register: timestamp
      tags: always
    
    - set_fact:
        curtmstmp: "{{ timestamp.stdout }}"
        finalreport: "/tmp/db2bkpreports/ps/finalreport_{{ timestamp.stdout }}.txt"
      tags: always
    
    - name: Consolidate report
      local_action: 
        module: script 
        cmd: "gen_ps_report.sh {{ finalreport }} /tmp/db2bkpreports/ps"
        args:
          executable: /bin/bash
      become: false
      run_once: true

    - name: Copy - Final report file to report server
      copy:
        src: "{{ finalreport }}"
        dest: /tmp/final_report_ps.txt
        mode: '0755'
      delegate_to: "{{ reportsserver }}"
      become: false
      run_once: true

    - name: Send - mail
      shell: |
              REPORTSDIR="{{ reportsdir }}"
              mail -s "DB2 LUW - Purescale Backup Report - $(date +'%Y-%m-%d')" {{ mailto }} < /tmp/final_report_ps.txt
              #mkdir -m 777 -p ${REPORTSDIR}
              #if [[ ! -d ${REPORTSDIR} ]]; then mkdir -m 777 -p ${REPORTSDIR}; fi
              #cat /tmp/final_report_ps.txt
              #mv /tmp/final_report_ps.txt ${REPORTSDIR}/final_report_ps_$(date +'%Y%m%d%H%M%S').txt
      args:
        executable: /bin/bash
      register: shout
      delegate_to: "{{ reportsserver }}"
      run_once: true

    - name: Remove - Local Directory
      local_action: 
          module: file
          path: /tmp/db2bkpreports/ps
          state: absent
      become: false
      run_once: true
      tags: removedir

    - name: Final Output
      debug: msg="{{ shout.stdout_lines}}"
      run_once: true
      tags: finalout