---
    - name: "Running - DB2 Postpatch (Post Backups to {{ bkpsdir }})"
      command: "{{ scriptsdir }}/postpatch.sh {{ item }}"
      register: postpatchcmd
      become: true
      become_user: "{{ item }}"
      loop: "{{ db2ilist.stdout_lines }}"
      failed_when: postpatchcmd.rc > 0
      tags: postpatch