---
  - stat: path='/tmp/prepatch.complete'
    register: prepatchcomplete

  - block:
      - debug: msg="Start - Prebackups"
        run_once: true

      - import_tasks: prepatch.yml
        when: installupdate == "update" or installupdate == "install_update"

      - file: path='/tmp/prepatch.complete' state='touch' mode='0777'

      - debug: msg="End - Prebackups"
        run_once: true
    when: not prepatchcomplete.stat.exists
    tags: prepatch

  - stat: path='/tmp/stopdb2.complete'
    register: stopdb2complete

  - block:
      - debug: msg="Start - StopDB2"
        run_once: true

      - import_tasks: stopdb2.yml
        when: installupdate == "update" or installupdate == "install_update"

      - file: path='/tmp/stopdb2.complete' state='touch' mode='0777'

      - debug: msg="End - StopDB2"
        run_once: true
    when: not stopdb2complete.stat.exists
    tags: stopdb2

  - stat: path='/tmp/installfp.complete'
    register: installfpcomplete

  - block:
      - debug: msg="Start - InstallFixpack"
        run_once: true

      - import_tasks: installfp.yml
        when: installupdate == "install_update"

      - file: path='/tmp/installfp.complete' state='touch' mode='0777'

      - debug: msg="End - InstallFixpack"
        run_once: true
    when: not installfpcomplete.stat.exists
    tags: install

  - stat: path='/tmp/updateinc.complete'
    register: updateinccomplete

  - block:
      - debug: msg="Start - iUpdate"
        run_once: true

      - import_tasks: updateinc.yml
        when: installupdate == "update" or installupdate == "install_update"

      - file: path='/tmp/updateinc.complete' state='touch' mode='0777'

      - debug: msg="End - iUpdate"
        run_once: true
    when: not updateinccomplete.stat.exists
    tags: iupdate

  - stat: path='/tmp/startdb2.complete'
    register: startdb2complete

  - block:
      - debug: msg="Start - StartDB2"
        run_once: true

      - import_tasks: startdb2.yml
        when: installupdate == "update" or installupdate == "install_update"

      - file: path='/tmp/startdb2.complete' state='touch' mode='0777'

      - debug: msg="End - StartDB2"
        run_once: true
    when: not startdb2complete.stat.exists
    tags: startdb2

  - stat: path='/tmp/postpatch.complete'
    register: postpatchcomplete

  - block:
      - debug: msg="Start - PostBackups"
        run_once: true

      - import_tasks: postpatch.yml
        when: installupdate == "update" or installupdate == "install_update"

      - file: path='/tmp/postpatch.complete' state='touch' mode='0777'

      - debug: msg="End - PostBackups"
        run_once: true
    when: not postpatchcomplete.stat.exists
    tags: postpatch

  #- import_tasks: tsamp_upgrade.yml
  #  when: installupdate == "update" or installupdate == "install_update"
  #  tags: update